### ISSUE TITLE
Error connecting to Cohesity cluster from powershell

### ISSUE THREAD

**Issue by StoreOp** [cohesity/cohesity-powershell-module#111]
I can connect to my Cohesity cluster (myClusterName.domain.com) using the UI.

However, I get an error when connecting through the following command:
                      Connect-CohesityCluster -Server **myClusterName.domain.com** -Credential (Get-Credential) 

The error is as follows:

 Connect-CohesityCluster : Failed to connect to the Cohesity Cluster
Failed to connect to the Cohesity Cluster
At line:1 char:1
+ Connect-CohesityCluster -Server myClusterName.domain.com -Crede ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-CohesityCluster], Exception
    + FullyQualifiedErrorId : System.Exception,Cohesity.Powershell.Cmdlets.Cluster.ConnectCohesityCluster
  

Please let me know how to debug/resolve.

**Comment by ashish-cohesity** [comment]
Ack, I'm seeing it too. Working on a fix.

**Comment by StoreOp** [comment]
Thanks Ashish.  Please let me know if there is any programmatic workaround available as well.

**Comment by bijayprasadtiwari** [comment]
@StoreOp , can you confirm if the FQDN, myClusterName.domain.com is associated with the virtual IP.

**Comment by ashish-cohesity** [comment]
Hi @StoreOp , my bad, as @bijayprasadtiwari  pointed out the commandlet is working with a FQDN to add to above, make sure:

1. If you use just hostname instead of FQDN , make sure the same host name is pingable from the machine from which you are running powershell from. 
2. Make sure your nslookup resolves to the cluster vip from the same machine. I'm closing this one.
